import { useState } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Plus,
  Edit,
  Trash2,
  CheckCircle,
  XCircle,
  HelpCircle,
  ChevronDown,
  ChevronUp,
} from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogClose,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";

type Faq = {
  id: number;
  question: string;
  answer: string;
  published: boolean;
};

const initialFaqs: Faq[] = [
  {
    id: 1,
    question: "What is carbon management?",
    answer:
      "Carbon management is the process of measuring, monitoring, and reducing carbon emissions generated by an organization or individual.",
    published: true,
  },
  {
    id: 2,
    question: "How can my company reduce its carbon footprint?",
    answer:
      "By improving energy efficiency, adopting renewable energy, optimizing supply chains, and encouraging sustainable practices.",
    published: true,
  },
  {
    id: 3,
    question: "What are Scope 1, 2, and 3 emissions?",
    answer:
      "Scope 1: Direct emissions from owned sources. Scope 2: Indirect emissions from purchased energy. Scope 3: All other indirect emissions in the value chain.",
    published: true,
  },
  {
    id: 4,
    question: "Which standards are used for carbon reporting?",
    answer:
      "Common standards include the GHG Protocol, ISO 14064, and CDP frameworks.",
    published: false,
  },
];

export default function Faqs() {
  const [faqs, setFaqs] = useState<Faq[]>(initialFaqs);
  const [expanded, setExpanded] = useState<number | null>(null);

  const [newFaq, setNewFaq] = useState({
    question: "",
    answer: "",
    published: true,
  });
  const [editFaqId, setEditFaqId] = useState<number | null>(null);
  const [editFaq, setEditFaq] = useState({
    question: "",
    answer: "",
    published: true,
  });

  // Statistics
  const totalFaqs = faqs.length;
  const publishedFaqs = faqs.filter((faq) => faq.published).length;
  const draftFaqs = faqs.filter((faq) => !faq.published).length;

  // CRUD Logic
  const handleCreateFaq = () => {
    if (!newFaq.question.trim() || !newFaq.answer.trim()) return;
    setFaqs([
      ...faqs,
      {
        id: Math.max(0, ...faqs.map((f) => f.id)) + 1,
        question: newFaq.question.trim(),
        answer: newFaq.answer.trim(),
        published: newFaq.published,
      },
    ]);
    setNewFaq({ question: "", answer: "", published: true });
  };

  const openEditFaq = (faq: Faq) => {
    setEditFaqId(faq.id);
    setEditFaq({
      question: faq.question,
      answer: faq.answer,
      published: faq.published,
    });
  };

  const handleSaveEditFaq = () => {
    if (editFaqId === null) return;
    setFaqs((prev) =>
      prev.map((faq) =>
        faq.id === editFaqId
          ? {
              ...faq,
              question: editFaq.question.trim(),
              answer: editFaq.answer.trim(),
              published: editFaq.published,
            }
          : faq
      )
    );
    setEditFaqId(null);
  };

  const handleDeleteFaq = (id: number) => {
    setFaqs(faqs.filter((faq) => faq.id !== id));
  };

  const handleToggleFaq = (id: number) => {
    setFaqs(
      faqs.map((faq) =>
        faq.id === id ? { ...faq, published: !faq.published } : faq
      )
    );
  };

  // Standard FAQ Accordion
  const faqsToShow = faqs.sort((a, b) => a.id - b.id);

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">
            Carbon Management FAQs
          </h1>
          <p className="text-muted-foreground mt-2">
            Manage and answer common questions for your knowledge base
          </p>
        </div>
        <Dialog>
          <DialogTrigger asChild>
            <Button className="bg-carbon-gradient hover:bg-carbon-600">
              <Plus className="mr-2 h-4 w-4" />
              Add FAQ
            </Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-[600px] bg-background border">
            <DialogHeader className="text-center">
              <DialogTitle>Add New FAQ</DialogTitle>
              <DialogDescription>
                Provide a question and answer for your carbon management FAQ
              </DialogDescription>
            </DialogHeader>
            <div className="grid gap-4 py-4 max-h-96 overflow-y-auto px-4">
              <div className="space-y-2">
                <Label htmlFor="faq-q">Question</Label>
                <Input
                  id="faq-q"
                  value={newFaq.question}
                  onChange={(e) =>
                    setNewFaq({ ...newFaq, question: e.target.value })
                  }
                  placeholder="e.g., What is carbon offsetting?"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="faq-a">Answer</Label>
                <Textarea
                  id="faq-a"
                  value={newFaq.answer}
                  onChange={(e) =>
                    setNewFaq({ ...newFaq, answer: e.target.value })
                  }
                  placeholder="Provide a concise and informative answer."
                />
              </div>
              <div className="flex items-center gap-2 mt-2">
                <Switch
                  checked={newFaq.published}
                  onCheckedChange={() =>
                    setNewFaq({ ...newFaq, published: !newFaq.published })
                  }
                  id="faq-published"
                />
                <Label htmlFor="faq-published">
                  {newFaq.published ? "Published" : "Draft"}
                </Label>
              </div>
            </div>
            <div className="flex justify-center px-4 pb-4">
              <Button
                onClick={handleCreateFaq}
                className="bg-carbon-gradient w-full"
              >
                Add FAQ
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {/* Statistics Cards */}
      <div className="grid gap-6 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total FAQs</CardTitle>
            <HelpCircle className="h-4 w-4 text-carbon-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-carbon-700">{totalFaqs}</div>
            <p className="text-xs text-muted-foreground">{publishedFaqs} published</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Published</CardTitle>
            <CheckCircle className="h-4 w-4 text-green-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-700">
              {publishedFaqs}
            </div>
            <p className="text-xs text-muted-foreground">
              {((publishedFaqs / totalFaqs) * 100 || 0).toFixed(0)}% of total
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Drafts</CardTitle>
            <XCircle className="h-4 w-4 text-yellow-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-yellow-700">{draftFaqs}</div>
            <p className="text-xs text-muted-foreground">
              {draftFaqs > 0 ? "Some content in draft" : "All published"}
            </p>
          </CardContent>
        </Card>
      </div>

      {/* FAQ Accordion List - Admin CRUD */}
      <Card>
        <CardHeader>
          <CardTitle>FAQ List</CardTitle>
          <CardDescription>
            Expand to view, edit, toggle publish, or delete FAQs
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="divide-y divide-border">
            {faqsToShow.map((faq) => (
              <li key={faq.id} className="py-3">
                {/* Accordion header */}
                <button
                  className="w-full flex justify-between items-center text-left py-2 focus:outline-none"
                  onClick={() => setExpanded(expanded === faq.id ? null : faq.id)}
                  aria-expanded={expanded === faq.id}
                >
                  <span className="font-medium text-base flex items-center gap-2">
                    {faq.question}
                    {!faq.published && (
                      <span className="ml-2 text-xs px-2 py-0.5 rounded bg-yellow-100 text-yellow-700 border border-yellow-300">
                        Draft
                      </span>
                    )}
                  </span>
                  {expanded === faq.id ? (
                    <ChevronUp className="w-5 h-5 text-muted-foreground" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-muted-foreground" />
                  )}
                </button>
                {/* Accordion body & CRUD actions */}
                {expanded === faq.id && (
                  <div className="mt-3 bg-muted/40 rounded p-4">
                    <div className="text-muted-foreground whitespace-pre-line mb-4">{faq.answer}</div>
                    <div className="flex flex-wrap gap-2 items-center">
                      {/* Toggle Publish */}
                      <div className="flex items-center gap-2">
                        <Switch
                          checked={faq.published}
                          onCheckedChange={() => handleToggleFaq(faq.id)}
                          id={`faq-pub-${faq.id}`}
                        />
                        <Label htmlFor={`faq-pub-${faq.id}`}>
                          {faq.published ? (
                            <span className="inline-flex items-center gap-1 text-green-600">
                              <CheckCircle className="w-4 h-4" /> Published
                            </span>
                          ) : (
                            <span className="inline-flex items-center gap-1 text-yellow-700">
                              <XCircle className="w-4 h-4" /> Draft
                            </span>
                          )}
                        </Label>
                      </div>
                      {/* Edit */}
                      <Dialog open={editFaqId === faq.id} onOpenChange={(open) => !open && setEditFaqId(null)}>
                        <DialogTrigger asChild>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => openEditFaq(faq)}
                          >
                            <Edit className="h-4 w-4" />
                            Edit
                          </Button>
                        </DialogTrigger>
                        <DialogContent className="sm:max-w-[600px] bg-background border">
                          <DialogHeader className="text-center">
                            <DialogTitle>Edit FAQ</DialogTitle>
                            <DialogDescription>
                              Update the question or answer
                            </DialogDescription>
                          </DialogHeader>
                          <div className="grid gap-4 py-4 max-h-96 overflow-y-auto px-4">
                            <div className="space-y-2">
                              <Label htmlFor="edit-faq-q">Question</Label>
                              <Input
                                id="edit-faq-q"
                                value={editFaq.question}
                                onChange={(e) =>
                                  setEditFaq({
                                    ...editFaq,
                                    question: e.target.value,
                                  })
                                }
                              />
                            </div>
                            <div className="space-y-2">
                              <Label htmlFor="edit-faq-a">Answer</Label>
                              <Textarea
                                id="edit-faq-a"
                                value={editFaq.answer}
                                onChange={(e) =>
                                  setEditFaq({
                                    ...editFaq,
                                    answer: e.target.value,
                                  })
                                }
                              />
                            </div>
                            <div className="flex items-center gap-2 mt-2">
                              <Switch
                                checked={editFaq.published}
                                onCheckedChange={() =>
                                  setEditFaq({
                                    ...editFaq,
                                    published: !editFaq.published,
                                  })
                                }
                                id="edit-faq-published"
                              />
                              <Label htmlFor="edit-faq-published">
                                {editFaq.published ? "Published" : "Draft"}
                              </Label>
                            </div>
                          </div>
                          <div className="flex justify-center px-4 pb-4 gap-2">
                            <Button
                              onClick={handleSaveEditFaq}
                              className="bg-carbon-gradient w-full"
                            >
                              Save Changes
                            </Button>
                            <DialogClose asChild>
                              <Button
                                variant="outline"
                                className="w-full"
                              >
                                Cancel
                              </Button>
                            </DialogClose>
                          </div>
                        </DialogContent>
                      </Dialog>
                      {/* Delete */}
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleDeleteFaq(faq.id)}
                      >
                        <Trash2 className="h-4 w-4" />
                        Delete
                      </Button>
                    </div>
                  </div>
                )}
              </li>
            ))}
            {faqsToShow.length === 0 && (
              <li className="py-6 text-center text-muted-foreground">No FAQs yet.</li>
            )}
          </ul>
        </CardContent>
      </Card>
    </div>
  );
}